spring:
  application:
    name: flea-market
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/dmart
    username: admin_uhjin
    password: admin_uhjin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: dasfadhasduanfafijofajfopfajwfahiufaf
  profiles:
    include: aws